### ISSUE TITLE
TODO: configmap based template shared among k8s cluster users

### ISSUE THREAD

**Issue by reborn1867** [reborn1867/kubectl-cwide#1]
## Feature
Adapt template file into yaml and load it in k8s configmap and make it a shared configuration if kubectl-cwide specifies remote template configuration.

TODO:
- Convert template folders a configmap friendly structured format, maybe yaml?
```yaml
g-v-k:
  default: 
      columnTemplate: NAME:.metadata.name,STATE:.status.state,HEALTH:{{ template "Health" . }}
      localTemplate: |
        {{- define "Health" }}
          {{- printf "%s" .status.health  }}
        {{- end }}
  custom1: ...
  custom2: ...
g-v-k2:
  default: ...
```
